version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

#    info_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: INFO
#        formatter: standard
#        filename: /tmp/info.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

#    error_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: ERROR
#        formatter: error
#        filename: /tmp/errors.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

#    debug_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: DEBUG
#        formatter: standard
#        filename: /tmp/debug.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

#    critical_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: CRITICAL
#        formatter: standard
#        filename: /tmp/critical.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

#    warn_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: WARN
#        formatter: standard
#        filename: /tmp/warn.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

root:
    level: INFO
    handlers: [console]
    propagate: no

loggers:

    server.MinitelConnection:
        level: DEBUG
        
    session:
        level: DEBUG

    3615page:
        level: DEBUG
        
    Ullapage:
        level: DEBUG